### PR TITLE
feat: add typescript

### PR DESCRIPTION
**Pull request by alfanjauhari**
In this first PR, I added a typescript to make it easier to find bugs during development.

This PR should have included all the relevant things for us to apply type safety in it, such as pages, components, and data.

I also added pre-push hooks so that we can take out errors that occur during the build before we push it to the repository.

Resolver for #9

### CODE REVIEW

**Comment by nauvalazhar** [comment]
Hi @alfanjauhari, thank you for your contribution! Could you use `type` instead of `interface`? And let's follow the previous rules to use a single quote.

**Comment by alfanjauhari** [comment]
> Hi @alfanjauhari, thank you for your contribution! Could you use `type` instead of `interface`? And let's follow the previous rules to use a single quote.

Hi, @nauvalazhar thanks for your feedback. I already change the `interface` keyword to `type` in typescript and use the single quote as a prettier config says.

But, i have some resources that give me the decision to choose interface instead type. https://stackoverflow.com/questions/37233735/interfaces-vs-types-in-typescript. But i think for now we don't need to argue about which are the best practice for that, bcz they have each pros and cons.

**Comment by nauvalazhar** [comment]
Thank you for your hard work on this, @alfanjauhari! I found `type` is easier to type and [**does not** extend automatically][0]. For now, I will merge this PR, and let's improve the rest gradually.

[0]: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

**Comment by nauvalazhar** [comment]
@all-contributors please add @alfanjauhari as code

**Pull request merged**
